name: phpstan

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon'
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpstan@v3
        with:
          path: packages/*/src
