name: phpstan

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon'
jobs:
  phpstan8_1:
    name: phpstan @ PHP 8.1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: php-actions/composer@v5
        with:
          php_version: 8.1

      - uses: php-actions/phpstan@v3
        with:
          php_version: 8.1
          level: 8
          configuration: 'phpstan.neon'
          version: '1.8.2'
          memory_limit: 256M
