name: Tests (PHP)

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '**.php'
      - 'phpunit.xml'
      - 'composer.json'
      - 'composer.lock'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php_version:
        - 7.4
        - 8.0
        - latest
    name: PHPUnit @ PHP ${{ matrix.php_version }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php_version }}

      - uses: php-actions/phpunit@v2
        with:
          php_version: ${{ matrix.php_version }}
