name: Tests (PHP)

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '**.php'
      - 'phpunit.xml'

jobs:
  phpunit8_1:
    name: PHPUnit @ PHP 8.1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: php-actions/composer@v6
        with:
          php_version: 8.1

      - uses: php-actions/phpunit@v9
        with:
          php_version: 8.1
