name: Split Monorepo

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  split_monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [
          'access-definitions',
          'dql',
          'extra',
          'paths',
          'queries',
          'jsonapi'
        ]

    steps:
      -   uses: actions/checkout@v2
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Split of ${{ matrix.package }}
        # TODO: reset to a released version once they say splitting works again
        uses: symplify/github-action-monorepo-split@2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'demos-europe'
          split-repository-name: 'edt-${{ matrix.package }}'
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'demos-europe'
          split-repository-name: 'edt-${{ matrix.package }}'
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"
